### ISSUE TITLE
OpenCV error: Cannot load info library for OpenCV

### ISSUE THREAD

**Issue by DyncKathline** [woshiwzy/opencv_wechat_qr#1]
![image](https://user-images.githubusercontent.com/16282974/112237493-c216b200-8c7d-11eb-9c20-e84f65ef9428.png)
直接运行控制台出现这个
2021-03-24 08:50:19.976 25209-25209/com.wangzy.qrdemo E/OpenCV/StaticHelper: OpenCV error: Cannot load info library for OpenCV
2021-03-24 08:50:20.195 25209-25209/com.wangzy.qrdemo E/m.wangzy.qrdem: No implementation found for long org.opencv.wechat_qrcode.WeChatQRCode.WeChatQRCode_0(java.lang.String, java.lang.String, java.lang.String, java.lang.String) (tried Java_org_opencv_wechat_1qrcode_WeChatQRCode_WeChatQRCode_10 and Java_org_opencv_wechat_1qrcode_WeChatQRCode_WeChatQRCode_10__Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2)
2021-03-24 08:50:20.196 25209-25209/com.wangzy.qrdemo E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.wangzy.qrdemo, PID: 25209
    java.lang.UnsatisfiedLinkError: No implementation found for long org.opencv.wechat_qrcode.WeChatQRCode.WeChatQRCode_0(java.lang.String, java.lang.String, java.lang.String, java.lang.String) (tried Java_org_opencv_wechat_1qrcode_WeChatQRCode_WeChatQRCode_10 and Java_org_opencv_wechat_1qrcode_WeChatQRCode_WeChatQRCode_10__Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2)
        at org.opencv.wechat_qrcode.WeChatQRCode.WeChatQRCode_0(Native Method)
        at org.opencv.wechat_qrcode.WeChatQRCode.<init>(WeChatQRCode.java:44)
        at com.wangzy.qrdemo.WechatQr.init(WechatQr.java:32)
        at com.wangzy.qrdemo.Qr1PortraitActivity.onResume(Qr1PortraitActivity.java:93)
        at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1456)
        at android.app.Activity.performResume(Activity.java:8135)
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4434)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4476)
        at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

**Comment by woshiwzy** [comment]
你是在模拟器上运行的么？如果是在模拟器上运行的我后来发现确实有问题

**Comment by woshiwzy** [comment]
在真机上运行

**Comment by woshiwzy** [comment]
在真机上运行

**Comment by DyncKathline** [comment]
> 在真机上运行

是在真机运行

**Comment by woshiwzy** [comment]
你试试这个编译好apk看看能不能跑起来呢，我这里没得问题，
https://github.com/woshiwzy/opencv_wechat_qr/blob/master/qrdemo-release.apk
你是啥手机型号？

**Comment by DyncKathline** [comment]
> 你试试这个编译好apk看看能不能跑起来呢，我这里没得问题，
> https://github.com/woshiwzy/opencv_wechat_qr/blob/master/qrdemo-release.apk
> 你是啥手机型号？

小米4，安装还是崩溃

**Comment by woshiwzy** [comment]
> > 你试试这个编译好apk看看能不能跑起来呢，我这里没得问题，
> > https://github.com/woshiwzy/opencv_wechat_qr/blob/master/qrdemo-release.apk
> > 你是啥手机型号？
> 
> 小米4，安装还是崩溃

我手机也是小米，不过新一点，看起来你手机armv7结构，估计这个包有点问题，我后面重新传一个so

**Comment by BraveMomo** [comment]
我这边的设备也遇到了同样的问题，请楼主重新传啊

**Comment by woshiwzy** [comment]
> 我这边的设备也遇到了同样的问题，请楼主重新传啊

兄弟你是用的什么手机？

**Comment by BraveMomo** [comment]
> > 我这边的设备也遇到了同样的问题，请楼主重新传啊
> 
> 兄弟你是用的什么手机？

是工业平板，不是普通消费者的设备

**Comment by woshiwzy** [comment]
> 我这边的设备也遇到了同样的问题，请楼主重新传啊

最新的so已经上传

**Comment by woshiwzy** [comment]
> > 你试试这个编译好apk看看能不能跑起来呢，我这里没得问题，
> > https://github.com/woshiwzy/opencv_wechat_qr/blob/master/qrdemo-release.apk
> > 你是啥手机型号？
> 
> 小米4，安装还是崩溃

最新的so已经上传
